

samplename: 'p5866'
section_id: '5866001'
mintime: 11900.58
maxtime: 11988.5
k: 0.0005
lc: 125
vel_windowlen: 20
filter_windowlen: 20
q: 4
ndr: 200000
nch: 4
ntune: 2000
ncores: 4
threshold: 0.15

a_prior:
  dist_type: 'LogNormal'
  mu: -5
  sigma: 0.8
  alpha: None
  beta: None
b_prior:
  dist_type: 'LogNormal'
  mu: -5
  sigma: 0.8
  alpha: None
  beta: None
Dc_prior:
  dist_type: 'Weibull'
  mu: None
  sigma: None
  alpha: 1.5
  beta: 40
mu0_prior:
  dist_type: 'LogNormal'
  mu: -1
  sigma: 0.3
  alpha: None
  beta: None
s_prior:
  dist_type: 'Weibull'
  mu: None
  sigma: None
  alpha: 1.5
  beta: 0.2

input_data_dir: 'C:\Users\fich146\PycharmProjects\mcmcrsf_xfiles\data\FORGE_DataShare'
output_mcmc_dirname: 'mcmc_out'




