

samplename: 'p5894'
section_id: '5894001'
mintime: 21342.39
maxtime: 21754.89
k: 0.00153
lc: 125
vel_windowlen: 10
filter_windowlen: 20
q: 5
ndr: 100
nch: 2
ntune: 2
ncores: 4
threshold: 0.1

a_prior:
  dist_type: 'LogNormal'
  mu: -5
  sigma: 0.8
b_prior:
  dist_type: 'LogNormal'
  mu: -5
  sigma: 0.8
Dc_prior:
  dist_type: 'LogNormal'
  mu: 4
  sigma: 0.5
mu0_prior:
  dist_type: 'LogNormal'
  mu: -1
  sigma: 0.3
s_prior:
  dist_type: 'HalfNormal'
  mu: None
  sigma: 0.01

input_data_dir: 'C:\Users\fich146\PycharmProjects\mcmcrsf_xfiles\data\FORGE_DataShare'
input_data_fname: 'p5894_proc.hdf5' # must be .hdf5 or should edit get_obs_data() in mcrasta.py

header_names:
  mu: 'mu'      # experimental friction data header
  t: 'time_s'   # exp. time header
  x: 'vdcdt_um' # exp. displacement header

output_mcmc_dir: 'mcmc_out'




